### ISSUE TITLE
Octoprint keeps trying to update 

### ISSUE THREAD

**Issue by giantpune** [foosel/OctoPrint#1134]
I've had octopi running flawlessly for months now.  In the past week or so, its been saying that there's an update.  I tell it to update.  It immediately says it was successful.  Rinse and repeat.  In the log, I have this
```sh
2015-12-08 17:04:34,124 - octoprint.plugins.softwareupdate - ERROR - Could not check octoprint for updates
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.7-py2.7.egg/octoprint/plugins/softwareupdate/__init__.py", line 471, in _get_current_version
    information, is_current = version_checker.get_latest(target, check)
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.7-py2.7.egg/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 140, in get_latest
    force_base=force_base)
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.7-py2.7.egg/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 93, in _is_current
    sanitized_local = _get_sanitized_version(release_information["local"]["value"])
  File "/home/pi/oprint/lib/python2.7/site-packages/OctoPrint-1.2.7-py2.7.egg/octoprint/plugins/softwareupdate/version_checks/github_release.py", line 48, in _get_sanitized_version
    if "-" in version_string:
TypeError: argument of type 'NoneType' is not iterable```

**Comment by foosel** [comment]
https://github.com/foosel/OctoPrint/wiki/FAQ#im-running-127-i-tried-to-update-to-a-newer-version-via-the-software-update-plugin-but-im-still-on-127-after-restart

https://github.com/foosel/OctoPrint/releases/tag/1.2.8

https://plus.google.com/u/0/b/110130855001142142895/+OctoprintOrg/posts/VAttLfxezFN
