### ISSUE TITLE
API error during File Upload

### ISSUE THREAD

**Issue by dtynan** [foosel/OctoPrint#2497]
#### What were you doing?

Uploading a file using the REST API (Octoprint v1.3.6). Specifically, a POST to /api/files/local

#### What did you expect to happen?

I was anticipating a 200 (or 20x) code to tell me the file had uploaded. Instead, I got a 500 (Internal Server Error).

#### What happened instead?

Here is the backtrace from the log:

`2018-03-20 14:17:35,471 - octoprint - ERROR - Exception on /api/files/local [POST]
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.6-py2.7.egg/octoprint/server/util/flask.py", line 1114, in decorated_view
    return flask.ext.login.login_required(func)(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/Flask_Login-0.2.11-py2.7.egg/flask_login.py", line 758, in decorated_view
    return func(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.6-py2.7.egg/octoprint/server/api/files.py", line 348, in uploadGcodeFile
    display=canonFilename)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.6-py2.7.egg/octoprint/filemanager/__init__.py", line 473, in add_file
    self._analysis_queue.dequeue(queue_entry)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/OctoPrint-1.3.6-py2.7.egg/octoprint/filemanager/analysis.py", line 86, in dequeue
    if not entry.type in self._queues:
AttributeError: 'NoneType' object has no attribute 'type'
2018-03-20 14:17:35,499 - tornado.access - ERROR - 500 POST /api/files/local (127.0.0.1) 163.43ms
`

Can you provide any pointers on how to debug this? What I should be looking at, etc? Any help appreciated.

#### Did the same happen when running OctoPrint in safe mode?

Same result.

#### Version of OctoPrint

v1.3.6 (OctoPi v 0.14.0)

#### Operating System running OctoPrint

OctoPi

`Linux octopi 4.9.28+ #998 Mon May 15 16:50:35 BST 2017 armv6l GNU/Linux`

#### Printer model & used firmware incl. version

Mendel90

#### Browser and version of browser, operating system running browser

N/A

#### Link to octoprint.log

Log file error (backtrace) reproduced above.

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by dtynan** [comment]
Argghh! the logfile extract looks awful. Try this:

https://gist.github.com/dtynan/310adfb73f0ec9de87092b28a64fc027

**Comment by dtynan** [comment]
Under the category of "might be relevant", I'm using the Ruby RestClient to do the post. As it's a multipart form, it's changing the **ContentType** from `application/json` to `multipart/form-data` as you'd expect, but the part where the GCode file is, has the **ContentType** set to `text/plain`. This still shouldn't cause a 500 error, but I'll look into why the RestClient isn't setting the right content type.

**Comment by dtynan** [comment]
I was using a Ruby Tempfile for the upload, which sets the filename to mostly random characters. I modified it to hard-code the file extension to .gcode and the problem has gone away!

Thanks a million!
