### ISSUE TITLE
GET on /api/slicing fails with 500 if slicer not configured yet

### ISSUE THREAD

**Issue by foosel** [foosel/OctoPrint#2508]
### Problem

Slicing GET API has a bit of an issue on 1.3.7rc1:

```
2018-03-20 11:53:29,134 - octoprint - ERROR - Exception on /api/slicing [GET]
Traceback (most recent call last):
  File "/home/test/OctoPrint/venv/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/test/OctoPrint/venv/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/test/OctoPrint/venv/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/test/OctoPrint/venv/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/test/OctoPrint/venv/local/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    RETURN self.view_functions[rule.endpoint](**req.view_args)
  File "/home/test/OctoPrint/src/octoprint/server/util/flask.py", line 975, in decorated_function
    lm = lastmodified_factory()
  File "/home/test/OctoPrint/src/octoprint/server/api/slicing.py", line 64, in <lambda>
    lastmodified_factory=lambda: _lastmodified(request.values.get("configured", "false") in valid_boolean_trues),
  File "/home/test/OctoPrint/src/octoprint/server/api/slicing.py", line 31, in _lastmodified
    lms.append(slicingManager.profiles_last_modified(slicer))
  File "/home/test/OctoPrint/src/octoprint/slicing/__init__.py", line 578, in profiles_last_modified
    RETURN self.get_slicer(slicer).get_slicer_profiles_lastmodified(slicer_profile_path)
  File "/home/test/OctoPrint/src/octoprint/slicing/__init__.py", line 204, in get_slicer
    raise SlicerNotConfigured(slicer)
SlicerNotConfigured
```

(Found in #2494)

That's a regression.

### Solution

Need to make it not demand a configured slicer just for fetching profiles.

**Comment by foosel** [comment]
1.3.7rc2 was released earlier today which should fix this issue.
