### ISSUE TITLE
Confusing startup error when uploads directory is broken symlink

### ISSUE THREAD

**Issue by cinderblock** [foosel/OctoPrint#2644]
#### What were you doing?

Starting octoprint

#### What did you expect to happen?

Startup or Show useful warning

#### What happened instead?

Stack trace

#### Did the same happen when running OctoPrint in safe mode?

Yes

#### Version of OctoPrint

`1.3.8`

#### Operating System running OctoPrint

Raspbian

#### octoprint.log

```
2018-05-15 14:05:34,711 - octoprint.startup - INFO - ******************************************************************************
2018-05-15 14:05:34,713 - octoprint.startup - INFO - Starting OctoPrint 1.3.8
2018-05-15 14:05:34,714 - octoprint.startup - INFO - Starting in SAFE MODE. Third party plugins will be disabled!
2018-05-15 14:05:34,715 - octoprint.startup - INFO - ******************************************************************************
2018-05-15 14:05:34,788 - octoprint.util.connectivity_checker - INFO - Connectivity changed from offline to online
2018-05-15 14:05:34,795 - octoprint.startup - INFO - Blacklist processing done
2018-05-15 14:05:34,883 - octoprint.plugin.core - INFO - Loading plugins from /opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-05-15 14:05:37,417 - octoprint.plugin.core - WARNING - Plugin "OctoPi Support Plugin" did not pass check
2018-05-15 14:05:39,899 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2018-05-15 14:05:39,920 - octoprint.plugin.core - INFO - Found 20 plugin(s) providing 9 mixin implementations, 4 hook handlers
2018-05-15 14:05:39,925 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2018-05-15 14:05:39,985 - octoprint.server - INFO - Intermediary server started
2018-05-15 14:05:39,987 - octoprint.plugin.core - INFO - Loading plugins from /opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-05-15 14:05:40,010 - octoprint.plugin.core - WARNING - Plugin "OctoPi Support Plugin" did not pass check
2018-05-15 14:05:41,246 - octoprint.plugin.core - INFO - Found 20 plugin(s) providing 9 mixin implementations, 4 hook handlers
2018-05-15 14:05:41,325 - octoprint.cli.server - ERROR - Uncaught exception
Traceback (most recent call last):
  File "/opt/OctoPrint/venv/bin/octoprint", line 11, in <module>
    load_entry_point('OctoPrint==1.3.8', 'console_scripts', 'octoprint')()
  File "/opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint/__init__.py", line 565, in main
    octo(args=args, prog_name="octoprint", auto_envvar_prefix="OCTOPRINT")
  File "/opt/OctoPrint/venv/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/opt/OctoPrint/venv/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/opt/OctoPrint/venv/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/opt/OctoPrint/venv/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/opt/OctoPrint/venv/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/opt/OctoPrint/venv/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint/cli/server.py", line 183, in serve_command
    ignore_blacklist)
  File "/opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint/cli/server.py", line 104, in run_server
    octoprint_server.run()
  File "/opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint/server/__init__.py", line 261, in run
    storage_managers[octoprint.filemanager.FileDestinations.LOCAL] = octoprint.filemanager.storage.LocalFileStorage(self._settings.getBaseFolder("uploads"))
  File "/opt/OctoPrint/venv/lib/python2.7/site-packages/octoprint/settings.py", line 1453, in getBaseFolder
    os.makedirs(folder)
  File "/opt/OctoPrint/venv/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/home/pi/.octoprint/uploads'
```

I have read the FAQ.

----

The issue here is simply that `/home/pi/.octoprint/uploads` is a broken symlink:
```
pi@raspberryprint:~ $ ls -l /home/pi/.octoprint/uploads
lrwxrwxrwx 1 pi pi 21 Apr 22  2017 /home/pi/.octoprint/uploads -> /mnt/remote-server/uploads
pi@raspberryprint:~ $ ls -l /mnt/remote-server/uploads
ls: cannot access /mnt/remote-server/uploads: No such file or directory
pi@raspberryprint:~ $ ls -l /mnt/remote-server/
total 0
```

The solution in my case was to remount the nfs mount that failed: `sudo mount /mnt/remote-server`

The reason I'm creating this issue is that I feel you might want to provide some more useful error messages when this happens. I was scratching my head for a good while wondering why octoprint wasn't starting up on its own. `ls /home/pi/.octoprint/uploads` showed that the file was there - it took me a while to remember/realize that it was a symlink that could be causing the problem. Also "file exists" seems like a weird error (I realize this is just the error reported by the underlying filesystem api).

If this report is unwarranted, my apologies. Regardless, thanks for the awesome software!

**Comment by foosel** [comment]
The above commit plus a couple of others will now make OctoPrint check for broken symlinks (and a bunch of other invalid folder situations) on startup and die with a meaningful log message if it encounters something it can't fix. It *will* try to fallback to the default configuration, but if that's not possible - poof.

Will looks something like this:

```
2018-06-18 13:40:44,343 - octoprint.startup - INFO - ******************************************************************************
2018-06-18 13:40:44,345 - octoprint.startup - INFO - Starting OctoPrint 1.3.9.dev219+g7043315
2018-06-18 13:40:44,345 - octoprint.startup - INFO - ******************************************************************************
2018-06-18 13:40:44,353 - octoprint.startup - CRITICAL - Configured folders didn't pass sanity check: Folder at /home/pi/.octoprint/uploads appears to be a broken symlink
2018-06-18 13:40:44,353 - octoprint.startup - CRITICAL - There was a fatal error starting up OctoPrint.
```

Already on `maintenance`, soon `devel`, to be released with 1.3.9
