### ISSUE TITLE
Upgrading OctoPi to Stretch fails to start Server afterwards

### ISSUE THREAD

**Issue by soundstorm** [foosel/OctoPrint#2655]
#### What were you doing?

Upgraded OctoPi (jessie) to stretch.

#### What did you expect to happen?

Normal operation

#### What happened instead?

```
python /home/pi/oprint/bin/octoprint --host=127.0.0.1 --port=5000
Traceback (most recent call last):
  File "/home/pi/oprint/bin/octoprint", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3019, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3003, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3032, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 655, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 963, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 849, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'OctoPrint==1.3.8' distribution was not found and is required by the application
```
#### Did the same happen when running OctoPrint in safe mode?

-/-

#### Version of OctoPrint

1.3.8

#### Operating System running OctoPrint

Raspberry Pi 3 stretch

#### Printer model & used firmware incl. version

-/-
#### Browser and version of browser, operating system running browser

-/-

#### Link to octoprint.log

-/-

#### Link to contents of terminal tab or serial.log

-/-

#### Link to contents of Javascript console in the browser

-/-

#### Screenshot(s)/video(s) showing the problem:

-/-

I have read the FAQ.

**Comment by soundstorm** [comment]
Tinkered around, working again.
