### ISSUE TITLE
Octoprint Updates Fail when invoked via CLI

### ISSUE THREAD

**Issue by prannonpendragas** [foosel/OctoPrint#2712]
#### What were you doing?

Attempting to update Octoprint + plugins using the command line tool. 

`/home/pi/oprint/bin/octoprint plugins softwareupdate:update`

#### What did you expect to happen?

Expected to see the plugin download and update octoprint, or display that there are no updates available.

It should be noted that the updates succeed when done via the browser UI.

#### What happened instead?

```
pi@Prusa005:~ $ /home/pi/oprint/bin/octoprint plugins softwareupdate:update
Initializing settings & plugin subsystem...
No handlers could be found for logger "octoprint.plugin.core"
Traceback (most recent call last):
  File "/home/pi/oprint/bin/octoprint", line 9, in <module>
    load_entry_point('OctoPrint==1.3.8', 'console_scripts', 'octoprint')()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/__init__.py", line 565, in main
    octo(args=args, prog_name="octoprint", auto_envvar_prefix="OCTOPRINT")
  File "/home/pi/oprint/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/click-6.2-py2.7.egg/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate/cli.py", line 133, in update_command
    prefix=prefix)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/cli/client.py", line 27, in create_client
    assert(host is not None or settings is not None)
AssertionError
```

#### Did the same happen when running OctoPrint in safe mode?

Yes.

#### Version of OctoPrint

OctoPrint 1.3.8 running on OctoPi 0.13.0, though this is also occurring in other versions (1.3.7 is known).

#### Operating System running OctoPrint

OctoPi 0.13.0
```
pi@Prusa005:~ $ sudo cat /etc/os-release 
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"
```

#### Link to octoprint.log

https://pastebin.com/gwQs8q7C

I have read the FAQ.

**Comment by foosel** [comment]
Fix pushed to `maintenance`, soon `devel`, will be part of 1.3.10.
