### ISSUE TITLE
OctoPrint-Telegram 1.3.9rc1 cant install Telegram plugin

### ISSUE THREAD

**Issue by seraserboy** [foosel/OctoPrint#2714]
#### What were you doing?

1. ...Installing Telegram plugin in 1.3.9rc1 version
2. ...
3. ...

#### What did you expect to happen?

Sucesfully installed

#### What happened instead?

Sucesfully installed but unknow plugin advice and octoprint cant show the plugin with plugin-manager
#### Did the same happen when running OctoPrint in safe mode?

No, this plugin is disabled, disabled, plugin manager can show normally

#### Version of OctoPrint

1.3.9rc1 and Banana M2U

#### Operating System running OctoPrint

Ubuntu 16.04.4

#### Printer model & used firmware incl. version

Anet A8 and Marlin

#### Browser and version of browser, operating system running browser

Chrome

#### Link to octoprint.log

https://pastebin.com/79WTwfdZ

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by foosel** [comment]
```
[...]
2018-07-05 03:01:43,026 - octoprint.plugin.core - ERROR - Error loading plugin telegram
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/plugin/core.py", line 847, in _import_plugin
    instance = imp.load_module(key, f, filename, description)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_telegram/__init__.py", line 2, in <module>
    from PIL import Image
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/PIL/Image.py", line 64, in <module>
    from . import _imaging as core
ImportError: /usr/lib/arm-linux-gnueabihf/libc.so: invalid ELF header
[...]
```

That looks like an issue outside of the control of OctoPrint. Either it's your environment that's the problem here, or the plugin trying to pull in a wrong library version. I'd suggest to report this with the plugin author, just to be sure, but I fear it's more a case of your environment - for some reason the PIL dependency is trying to load a binary with a header that doesn't fit your operating system/processor.

**Comment by seraserboy** [comment]
Ok, but you can Install this plugin un 1.3.9rc1 fine?

**Comment by foosel** [comment]
Yep!

```
Installing plugin "OctoPrint-Telegram" from https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zip...
/home/pi/oprint/bin/python2 -m pip install https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zip --no-cache-dir
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zip
Downloading https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zip (98kB)
Requirement already satisfied: OctoPrint in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint-Telegram==1.4.2) (1.3.9rc1)
Collecting pillow (from OctoPrint-Telegram==1.4.2)
Downloading https://files.pythonhosted.org/packages/d3/c4/b45b9c0d549f482dd072055e2d3ced88f3b977f7b87c7a990228b20e7da1/Pillow-5.2.0.tar.gz (14.5MB)
Requirement already satisfied: watchdog<0.9,>=0.8.3 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.8.3)
Requirement already satisfied: python-dateutil<2.7,>=2.6.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.6.1)
Requirement already satisfied: feedparser<5.3,>=5.2.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (5.2.1)
Requirement already satisfied: requests<3,>=2.18.4 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.18.4)
Requirement already satisfied: flask<0.11,>=0.10.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.10.1)
Requirement already satisfied: scandir<1.4,>=1.3 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.3)
Requirement already satisfied: monotonic<1.4,>=1.3 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.3)
Requirement already satisfied: frozendict<1.3,>=1.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.2)
Requirement already satisfied: Jinja2<2.9,>=2.8.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.8.1)
Requirement already satisfied: emoji<0.5,>=0.4.5 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.4.5)
Requirement already satisfied: netifaces<0.11,>=0.10.6 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.10.6)
Requirement already satisfied: Flask-Babel<0.10,>=0.9 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.9)
Requirement already satisfied: pkginfo<1.5,>=1.4.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.4.2)
Requirement already satisfied: markdown<2.7,>=2.6.9 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.6.11)
Requirement already satisfied: pyserial<3.5,>=3.4 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (3.4)
Requirement already satisfied: semantic-version<2.5,>=2.4.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (2.4.2)
Requirement already satisfied: werkzeug<0.9,>=0.8.3 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.8.3)
Requirement already satisfied: websocket-client<0.41,>=0.40.0 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.40.0)
Requirement already satisfied: psutil<5.5,>=5.4.6 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (5.4.6)
Requirement already satisfied: awesome-slugify<1.7,>=1.6.5 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.6.5)
Requirement already satisfied: Flask-Login<0.3,>=0.2.11 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.2.11)
Requirement already satisfied: Flask-Principal<0.4,>=0.3.5 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.3.5)
Requirement already satisfied: rsa<3.3,>=3.2.3 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (3.2.3)
Requirement already satisfied: pylru<1.1,>=1.0.9 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.0.9)
Requirement already satisfied: Flask-Assets<0.11,>=0.10 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.10)
Requirement already satisfied: netaddr<0.8,>=0.7.19 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.7.19)
Requirement already satisfied: future<0.16,>=0.15.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.15.2)
Requirement already satisfied: Click<6.3,>=6.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (6.2)
Requirement already satisfied: sarge==0.1.4 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (0.1.4)
Requirement already satisfied: chainmap<1.1,>=1.0.2 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.0.2)
Requirement already satisfied: wrapt<1.11,>=1.10.11 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (1.10.11)
Requirement already satisfied: futures<3.2,>=3.1.1 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (3.1.1)
Requirement already satisfied: PyYAML<3.11,>=3.10 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (3.10)
Requirement already satisfied: tornado==4.5.3 in /home/pi/oprint/lib/python2.7/site-packages (from OctoPrint->OctoPrint-Telegram==1.4.2) (4.5.3)
Requirement already satisfied: argh>=0.24.1 in /home/pi/oprint/lib/python2.7/site-packages (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-Telegram==1.4.2) (0.26.2)
Requirement already satisfied: pathtools>=0.1.1 in /home/pi/oprint/lib/python2.7/site-packages (from watchdog<0.9,>=0.8.3->OctoPrint->OctoPrint-Telegram==1.4.2) (0.1.2)
Requirement already satisfied: six>=1.5 in /home/pi/oprint/lib/python2.7/site-packages (from python-dateutil<2.7,>=2.6.1->OctoPrint->OctoPrint-Telegram==1.4.2) (1.11.0)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/pi/oprint/lib/python2.7/site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-Telegram==1.4.2) (1.22)
Requirement already satisfied: idna<2.7,>=2.5 in /home/pi/oprint/lib/python2.7/site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-Telegram==1.4.2) (2.6)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/pi/oprint/lib/python2.7/site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-Telegram==1.4.2) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /home/pi/oprint/lib/python2.7/site-packages (from requests<3,>=2.18.4->OctoPrint->OctoPrint-Telegram==1.4.2) (2018.4.16)
Requirement already satisfied: itsdangerous>=0.21 in /home/pi/oprint/lib/python2.7/site-packages (from flask<0.11,>=0.10.1->OctoPrint->OctoPrint-Telegram==1.4.2) (0.24)
Requirement already satisfied: MarkupSafe in /home/pi/oprint/lib/python2.7/site-packages (from Jinja2<2.9,>=2.8.1->OctoPrint->OctoPrint-Telegram==1.4.2) (1.0)
Requirement already satisfied: Babel>=1.0 in /home/pi/oprint/lib/python2.7/site-packages (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-Telegram==1.4.2) (2.5.3)
Requirement already satisfied: speaklater>=1.2 in /home/pi/oprint/lib/python2.7/site-packages (from Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-Telegram==1.4.2) (1.3)
Requirement already satisfied: Unidecode<0.05,>=0.04.14 in /home/pi/oprint/lib/python2.7/site-packages (from awesome-slugify<1.7,>=1.6.5->OctoPrint->OctoPrint-Telegram==1.4.2) (0.4.21)
Requirement already satisfied: regex in /home/pi/oprint/lib/python2.7/site-packages (from awesome-slugify<1.7,>=1.6.5->OctoPrint->OctoPrint-Telegram==1.4.2) (2018.2.21)
Requirement already satisfied: blinker in /home/pi/oprint/lib/python2.7/site-packages (from Flask-Principal<0.4,>=0.3.5->OctoPrint->OctoPrint-Telegram==1.4.2) (1.4)
Requirement already satisfied: pyasn1>=0.1.3 in /home/pi/oprint/lib/python2.7/site-packages (from rsa<3.3,>=3.2.3->OctoPrint->OctoPrint-Telegram==1.4.2) (0.4.2)
Requirement already satisfied: webassets>=0.10 in /home/pi/oprint/lib/python2.7/site-packages (from Flask-Assets<0.11,>=0.10->OctoPrint->OctoPrint-Telegram==1.4.2) (0.12.1)
Requirement already satisfied: singledispatch in /home/pi/oprint/lib/python2.7/site-packages (from tornado==4.5.3->OctoPrint->OctoPrint-Telegram==1.4.2) (3.4.0.3)
Requirement already satisfied: backports-abc>=0.4 in /home/pi/oprint/lib/python2.7/site-packages (from tornado==4.5.3->OctoPrint->OctoPrint-Telegram==1.4.2) (0.5)
Requirement already satisfied: pytz>=0a in /home/pi/oprint/lib/python2.7/site-packages (from Babel>=1.0->Flask-Babel<0.10,>=0.9->OctoPrint->OctoPrint-Telegram==1.4.2) (2018.4)
Installing collected packages: pillow, OctoPrint-Telegram
Running setup.py install for pillow: started
Running setup.py install for pillow: finished with status 'done'
Running setup.py install for OctoPrint-Telegram: started
Running setup.py install for OctoPrint-Telegram: finished with status 'done'
Successfully installed OctoPrint-Telegram-1.4.2 pillow-5.2.0
Done!
```

```
2018-07-05 11:26:26,944 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-07-05 11:26:26,948 - octoprint.server - INFO - --- Log roll over detected ---------------------------------------------------
2018-07-05 11:26:26,949 - octoprint.server - INFO - OctoPrint 1.3.9rc1
2018-07-05 11:26:26,952 - octoprint.plugin.core - INFO - 13 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  CuraEngine (<= 15.04) (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/cura
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/discovery
|  Github release patcher (0.1.0) = /home/pi/.octoprint/plugins/github_release_patcher.py
|  Logging (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/logging
|  OctoPi Support Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/octopi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Printer Safety Check (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/printer_safety_check
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_yamlpatcher
2018-07-05 11:26:26,979 - octoprint.environment - INFO - Detected environment is Python 2.7.13 under Linux (linux2). Details:
|  hardware:
|    cores: 4
|    freq: 1400.0
|    ram: 918192128
|  os:
|    id: linux
|    platform: linux2
|  plugins:
|    octopi_support:
|      model: unknown
|      revision: a020d3
|      version: 0.15.0
|  python:
|    pip: 10.0.1
|    version: 2.7.13
|    virtualenv: /home/pi/oprint
2018-07-05 11:26:26,980 - octoprint.server - INFO - ------------------------------------------------------------------------------
2018-07-05 11:41:26,946 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-07-05 11:56:26,948 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-07-05 12:11:26,950 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-07-05 12:26:26,952 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-07-05 12:41:26,954 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-07-05 12:56:26,956 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-07-05 13:11:26,958 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-07-05 13:24:50,750 - octoprint.server.util.flask.PreemptiveCache - INFO - Adding entry for / and {'query_string': 'l10n=en', 'path': u'/', '_count': 1, '_timestamp': 1530797090.750363, 'base_url': 'http://octopi3p.local/'}
2018-07-05 13:24:57,889 - octoprint.server.util.sockjs - INFO - New connection from client: ::ffff:192.168.1.3
2018-07-05 13:25:03,716 - octoprint.plugins.announcements - INFO - Loaded channel _important from https://octoprint.org/feeds/important.xml in 0.32s
2018-07-05 13:25:04,245 - octoprint.plugins.announcements - INFO - Loaded channel _releases from https://octoprint.org/feeds/releases.xml in 0.27s
2018-07-05 13:25:04,576 - octoprint.plugins.announcements - INFO - Loaded channel _blog from https://octoprint.org/feeds/octoblog.xml in 0.26s
2018-07-05 13:25:04,923 - octoprint.plugins.announcements - INFO - Loaded channel _plugins from https://plugins.octoprint.org/feed.xml in 0.27s
2018-07-05 13:25:05,320 - octoprint.plugins.announcements - INFO - Loaded channel _octopi from https://octoprint.org/feeds/octopi.xml in 0.3s
2018-07-05 13:25:05,726 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2018-07-05 13:25:15,938 - octoprint.plugins.pluginmanager - INFO - Installing plugin from https://github.com/fabianonline/OctoPrint-Telegram/archive/stable.zip
2018-07-05 13:26:26,960 - octoprint.server.heartbeat - INFO - Server heartbeat <3
2018-07-05 13:26:29,070 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-07-05 13:26:29,724 - octoprint.plugin.core - INFO - Found 15 plugin(s) providing 13 mixin implementations, 10 hook handlers
2018-07-05 13:26:29,727 - octoprint.plugin.core - INFO - 15 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  CuraEngine (<= 15.04) (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/cura
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/discovery
|  Fix Lerdge 3D temperature responses = /home/pi/.octoprint/plugins/fix_lerdge3d_temp.py
|  Github release patcher (0.1.0) = /home/pi/.octoprint/plugins/github_release_patcher.py
|  Logging (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/logging
|  OctoPi Support Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/octopi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Printer Safety Check (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/printer_safety_check
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
| !Telegram Notifications (1.4.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_telegram
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_yamlpatcher
2018-07-05 13:26:29,728 - octoprint.plugins.pluginmanager - INFO - The plugin was installed successfully: Telegram Notifications, version 1.4.2
2018-07-05 13:26:42,455 - octoprint.server.api.system - INFO - Performing command for core:restart: sudo service octoprint restart
2018-07-05 13:26:42,624 - octoprint.server - INFO - Shutting down...
2018-07-05 13:26:43,163 - octoprint.events - INFO - Processing shutdown event, this will be our last event
2018-07-05 13:26:43,169 - octoprint.events - INFO - Event loop shut down
2018-07-05 13:26:43,176 - octoprint.server - INFO - Goodbye!
2018-07-05 13:26:44,808 - octoprint.startup - INFO - ******************************************************************************
2018-07-05 13:26:44,810 - octoprint.startup - INFO - Starting OctoPrint 1.3.9rc1
2018-07-05 13:26:44,811 - octoprint.startup - INFO - ******************************************************************************
2018-07-05 13:26:45,827 - octoprint.util.connectivity_checker - INFO - Connectivity changed from offline to online
2018-07-05 13:26:46,078 - octoprint.startup - INFO - Blacklist processing done
2018-07-05 13:26:46,116 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-07-05 13:26:47,929 - octoprint.plugin.core - INFO - Found 15 plugin(s) providing 14 mixin implementations, 12 hook handlers
2018-07-05 13:26:48,029 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2018-07-05 13:26:48,055 - octoprint.server - INFO - Intermediary server started
2018-07-05 13:26:48,056 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-07-05 13:26:48,609 - octoprint.plugin.core - INFO - Found 15 plugin(s) providing 14 mixin implementations, 12 hook handlers
2018-07-05 13:26:48,647 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octoprint/uploads...
2018-07-05 13:26:48,649 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads initialized successfully.
2018-07-05 13:26:48,799 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2018-07-05 13:26:50,306 - octoprint.util.pip - INFO - Using "/home/pi/oprint/bin/python2 -m pip" as command to invoke pip
2018-07-05 13:26:51,800 - octoprint.util.pip - INFO - Version of pip is 10.0.1
2018-07-05 13:26:51,802 - octoprint.util.pip - INFO - pip installs to /home/pi/oprint/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2018-07-05 13:26:51,803 - octoprint.util.pip - INFO - ==> pip ok -> yes
2018-07-05 13:26:51,806 - octoprint.plugin.core - INFO - Initialized 14 plugin implementation(s)
2018-07-05 13:26:51,816 - octoprint.plugins.telegram - DEBUG - MIGRATE DO
2018-07-05 13:26:51,818 - octoprint.plugins.telegram - DEBUG - LOADED CHATS: {}
2018-07-05 13:26:51,821 - octoprint.plugins.telegram - DEBUG - MIGRATED Chats: {}
2018-07-05 13:26:51,832 - octoprint.plugins.telegram - DEBUG - MESSAGES: {'StatusPrinting': {'bind_msg': 'ZChange', 'combined': True, 'no_setting': True}, 'PrintDone': {'text': 'Finished printing {file}.', 'image': True, 'combined': True, 'markup': 'off'}, 'ZChange': {'text': 'Printing at Z={z}.\nBed {bed_temp}/{bed_target}, Extruder {e1_temp}/{e1_target}.\n{time_done}, {percent}% done, {time_left} remaining.', 'image': True, 'combined': True, 'markup': 'off'}, 'PrinterStart': {'text': "{emo:rocket} Hello. I'm online and ready to receive your commands.", 'image': False, 'combined': True, 'markup': 'off'}, 'PrintFailed': {'text': 'Printing {file} failed.', 'image': True, 'combined': True, 'markup': 'off'}, 'StatusNotPrinting': {'text': 'Not printing.\nBed {bed_temp}/{bed_target}, Extruder {e1_temp}/{e1_target}.', 'image': True, 'combined': True, 'no_setting': True, 'markup': 'off'}, 'PrintStarted': {'text': 'Started printing {file}.', 'image': True, 'combined': True, 'markup': 'off'}, 'PrintResumed': {'text': 'Resumed printing {file} at {percent}%. {time_left} remaining.', 'image': True, 'combined': True, 'markup': 'off'}, 'PrintPaused': {'text': 'Paused printing {file} at {percent}%. {time_left} remaining.', 'image': True, 'combined': True, 'markup': 'off'}, 'PrinterShutdown': {'text': '{emo:octo} {emo:shutdown} Shutting down. Goodbye.', 'image': False, 'combined': True, 'markup': 'off'}}
2018-07-05 13:26:51,832 - octoprint.plugins.telegram - DEBUG - SAVED Chats: {}
2018-07-05 13:26:52,060 - octoprint.plugins.telegram - DEBUG - MIGRATED Saved
2018-07-05 13:26:52,198 - octoprint.plugin.core - INFO - 15 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Core Wizard (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  CuraEngine (<= 15.04) (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/cura
|  Discovery (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/discovery
|  Fix Lerdge 3D temperature responses = /home/pi/.octoprint/plugins/fix_lerdge3d_temp.py
|  Github release patcher (0.1.0) = /home/pi/.octoprint/plugins/github_release_patcher.py
|  Logging (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/logging
|  OctoPi Support Plugin (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/octopi_support
|  Plugin Manager (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Printer Safety Check (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/printer_safety_check
|  Software Update (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  Telegram Notifications (1.4.2) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_telegram
|  Virtual Printer (bundled) = /home/pi/oprint/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
|  Yamlpatcher (0.1.1) = /home/pi/oprint/local/lib/python2.7/site-packages/octoprint_yamlpatcher
2018-07-05 13:26:52,216 - octoprint.environment - INFO - Detected environment is Python 2.7.13 under Linux (linux2). Details:
|  hardware:
|    cores: 4
|    freq: 1400.0
|    ram: 918192128
|  os:
|    id: linux
|    platform: linux2
|  plugins:
|    octopi_support:
|      model: unknown
|      revision: a020d3
|      version: 0.15.0
|  python:
|    pip: 10.0.1
|    version: 2.7.13
|    virtualenv: /home/pi/oprint
```

I find it interesting though that it installed pillow for me, but apparently PIL for you.

**Comment by seraserboy** [comment]
Thank you Gina.

Finally working after some hours of Google and test.

cd /lib/arm-linux-gnueabihf
sudo ln -s libc.so.6 libc.so

This is the solution.
