### ISSUE TITLE
[1.3.9rc1] print time estimator uninitialized when print is started from the printer's controller, leading to exception

### ISSUE THREAD

**Issue by foosel** [foosel/OctoPrint#2715]
### Problem

See https://github.com/foosel/OctoPrint/issues/2688#issuecomment-402613919

```
2018-07-05 05:17:16,231 - octoprint.util.comm - INFO - Externally triggered heatup detected
2018-07-05 05:18:34,517 - octoprint.util.comm - INFO - Printer seems to support the busy protocol, telling it to set the busy interval to our "communicationBusy" timeout - 1s = 2s
2018-07-05 05:19:27,589 - octoprint.util.comm - INFO - Timeout while in an active heatup, considering heatup to be over.
2018-07-05 05:19:30,594 - octoprint.util.comm - INFO - Communication timeout while idle, trying to trigger response from printer.
2018-07-05 05:19:32,426 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Printing from SD"
2018-07-05 05:19:32,512 - octoprint.plugins.Octoslack - ERROR - Error processing event: PrintStarted, Error: 'Printer' object has no attribute '_estimator'
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_Octoslack/__init__.py", line 591, in handle_event
    self.process_slack_event(event, event_settings, channel_override, payload)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint_Octoslack/__init__.py", line 648, in process_slack_event
    printer_data = self._printer.get_current_data()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/server/__init__.py", line 384, in wrapper
    return f(*args, **kwargs)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 565, in get_current_data
    return util.thaw_frozendict(self._stateMonitor.get_current_data())
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 1326, in get_current_data
    self._progress = self._get_current_progress()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 1255, in _get_current_progress
    return self._on_get_progress()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 773, in _updateProgressDataCallback
    printTimeLeft, printTimeLeftOrigin = self._estimator.estimate(progress,
AttributeError: 'Printer' object has no attribute '_estimator'
2018-07-05 05:20:41,680 - octoprint.util.comm - INFO - Communication timeout while printing, trying to trigger response from printer.
2018-07-05 05:20:41,718 - octoprint.util.comm - INFO - Changing monitoring state from "Printing from SD" to "Cancelling"
2018-07-05 05:20:41,880 - octoprint.util.comm - INFO - Changing monitoring state from "Cancelling" to "Operational"
2018-07-05 05:21:35,678 - octoprint.server.api.system - INFO - Performing command for core:restart: sudo service octoprint restart
```

Closer inspection of the implementation reveals that not only is `self._estimator` only set if the print is started through OctoPrint, it's also not even defined in `__init__` and also no check is done in the progress callback.

*edit* Also causes an uncaught exception in the state update thread, killing this in the process (see comment below).

### Solution

Define `self._estimator` in constructor, make sure it's set whenever a file is selected (regardless of how) and also add a sanity check in the progress callback to only try to call `self._estimator.estimate` if the estimator is not `None`.

*edit* Improve error handling in update worker, it should at least not be killed by issues like this.

**Comment by foosel** [comment]
Also leads to an uncaught exception without the above plugin in place that kill the state update worker:

```
2018-07-05 09:40:25,046 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Printing from SD"
2018-07-05 09:40:25,049 - octoprint.filemanager.analysis - DEBUG - Pausing analysis
Exception in thread Thread-14:
Traceback (most recent call last):
  File "c:\python27\Lib\threading.py", line 801, in __bootstrap_inner
    self.run()
  File "c:\python27\Lib\threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "C:\Devel\OctoPrint\OctoPrint\src\octoprint\printer\standard.py", line 1318, in _work
    data = self.get_current_data()
  File "C:\Devel\OctoPrint\OctoPrint\src\octoprint\printer\standard.py", line 1326, in get_current_data
    self._progress = self._get_current_progress()
  File "C:\Devel\OctoPrint\OctoPrint\src\octoprint\printer\standard.py", line 1255, in _get_current_progress
    return self._on_get_progress()
  File "C:\Devel\OctoPrint\OctoPrint\src\octoprint\printer\standard.py", line 773, in _updateProgressDataCallback
    printTimeLeft, printTimeLeftOrigin = self._estimator.estimate(progress,
AttributeError: 'Printer' object has no attribute '_estimator'
```
