### ISSUE TITLE
Server Internal error

### ISSUE THREAD

**Issue by gege2b** [foosel/OctoPrint#2778]
hi there

#### What were you doing?

I was messing with upgrades (I had the sarge 0.1.5 bug so I downgraded it to 0.1.4)
Now I'm running OP 1.3.9 and I get an internal error, looking in the log there is something about json (see above)

#### What did you expect to happen?
being able to access the UI

#### What happened instead?
Error 500

#### Did the same happen when running OctoPrint in safe mode?

Yes, same problem

#### Version of OctoPrint

1.3.9 latest

#### Operating System running OctoPrint

raspbian stable

#### Printer model & used firmware incl. version

n/a

#### Browser and version of browser, operating system running browser

firefox 61 on win10

#### Link to octoprint.log

```
2018-08-03 16:01:17,002 - octoprint.startup - INFO - ****************************************************************                                                                                                                        **************
2018-08-03 16:01:17,004 - octoprint.startup - INFO - Starting OctoPrint 1.3.9
2018-08-03 16:01:17,005 - octoprint.startup - INFO - ****************************************************************                                                                                                                        **************
2018-08-03 16:01:17,070 - octoprint.util.connectivity_checker - INFO - Connectivity changed from offline to online
2018-08-03 16:01:17,075 - octoprint.startup - INFO - Blacklist processing done
2018-08-03 16:01:17,114 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/OctoPrint/venv/lib/python2.7/s                                                                                                                        ite-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-08-03 16:01:18,402 - octoprint.plugin.core - WARNING - Plugin "OctoPi Support Plugin" did not pass check
2018-08-03 16:01:19,611 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't b                                                                                                                        e available
2018-08-03 16:01:19,629 - octoprint.plugin.core - INFO - Found 16 plugin(s) providing 16 mixin implementations, 20 ho                                                                                                                        ok handlers
2018-08-03 16:01:19,740 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2018-08-03 16:01:19,769 - octoprint.server - INFO - Intermediary server started
2018-08-03 16:01:19,770 - octoprint.plugin.core - INFO - Loading plugins from /home/pi/OctoPrint/venv/lib/python2.7/s                                                                                                                        ite-packages/octoprint/plugins, /home/pi/.octoprint/plugins and installed plugin packages...
2018-08-03 16:01:19,780 - octoprint.plugin.core - WARNING - Plugin "OctoPi Support Plugin" did not pass check
2018-08-03 16:01:21,134 - octoprint.plugin.core - INFO - Found 16 plugin(s) providing 16 mixin implementations, 20 ho                                                                                                                        ok handlers
2018-08-03 16:01:21,218 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/pi/.octopri                                                                                                                        nt/uploads...
2018-08-03 16:01:22,971 - octoprint.filemanager.storage - INFO - ... file metadata for /home/pi/.octoprint/uploads in                                                                                                                        itialized successfully.
2018-08-03 16:01:23,174 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2018-08-03 16:01:24,973 - octoprint.util.pip - INFO - Using "/home/pi/OctoPrint/venv/bin/python2 -m pip" as command to invoke pip
2018-08-03 16:01:26,761 - octoprint.util.pip - INFO - Version of pip is 18.0
2018-08-03 16:01:26,763 - octoprint.util.pip - INFO - pip installs to /home/pi/OctoPrint/venv/lib/python2.7/site-packages (writable -> yes), --user flag needed -> no, virtual env -> yes
2018-08-03 16:01:26,763 - octoprint.util.pip - INFO - ==> pip ok -> yes
2018-08-03 16:01:26,770 - octoprint.plugin.core - INFO - Initialized 16 plugin implementation(s)
2018-08-03 16:01:26,783 - octoprint.plugin.core - INFO - 16 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/announcements
|  Core Wizard (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/corewizard
|  CuraEngine (<= 15.04) (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/cura
|  Discovery (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/discovery
|  FileManager (0.1.2) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_filemanager
|  Firmware Updater (1.0.0) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_firmwareupdater
|  GcodeEditor (0.2.6) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_GcodeEditor
|  Logging (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/logging
|  Navbar Temperature Plugin (0.9) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_navbartemp
|  Octolapse (0.3.2) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_octolapse
|  Plugin Manager (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/pluginmanager
|  Printer Safety Check (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/printer_safety_check
|  Software Update (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/softwareupdate
|  TouchUI (0.3.11) = /home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint_touchui
|  Virtual Printer (bundled) = /home/pi/OctoPrint/venv/lib/python2.7/site-packages/octoprint/plugins/virtual_printer
2018-08-03 16:01:26,800 - octoprint.environment - INFO - Detected environment is Python 2.7.13 under Linux (linux2). Details:
|  hardware:
|    cores: 4
|    freq: 1200.0
|    ram: 1024188416
|  os:
|    id: linux
|    platform: linux2
|  python:
|    pip: '18.0'
|    version: 2.7.13
|    virtualenv: /home/pi/OctoPrint/venv
2018-08-03 16:01:26,809 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/webassets...
2018-08-03 16:01:26,813 - octoprint.server - INFO - Reset webasset folder /home/pi/.octoprint/generated/.webassets-cache...
2018-08-03 16:01:26,834 - octoprint.plugins.octolapse - INFO - Octolapse is loading assets.
2018-08-03 16:01:27,272 - octoprint.server - INFO - Shutting down intermediary server...
2018-08-03 16:01:27,717 - octoprint.server - INFO - Intermediary server shut down
2018-08-03 16:01:27,723 - octoprint.events - INFO - Processing startup event, this is our first event
2018-08-03 16:01:27,724 - octoprint.events - INFO - Adding 1 events to queue that were held back before startup event
2018-08-03 16:01:27,744 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2018-08-03 16:01:27,800 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2018-08-03 16:01:28,804 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2018-08-03 16:01:29,473 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2018-08-03 16:01:29,666 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Opening serial port"
2018-08-03 16:01:29,671 - octoprint.util.comm - INFO - Changing monitoring state from "Opening serial port" to "Connecting"
2018-08-03 16:01:29,693 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2018-08-03 16:01:29,701 - octoprint.plugins.cura - INFO - Path to CuraEngine has not been configured or does not exist (currently set to None), Cura will not be selectable for slicing
2018-08-03 16:01:29,745 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance "Deep Thought" for SSDP
2018-08-03 16:01:29,757 - octoprint.server - INFO - Listening on http://[::]:5000
2018-08-03 16:01:29,936 - octoprint.plugins.octolapse - INFO - Loading existing settings file from: /home/pi/.octoprint/data/octolapse/settings.json.
2018-08-03 16:01:30,320 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2018-08-03 16:01:30,971 - octoprint.util.comm - INFO - Changing monitoring state from "Connecting" to "Operational"
2018-08-03 16:01:31,009 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2018-08-03 16:01:31,021 - octoprint.plugins.firmwareupdater - INFO - Got CONNECTED event
2018-08-03 16:01:31,024 - octoprint.plugins.firmwareupdater - INFO - Run postflash flag is not set
2018-08-03 16:01:31,187 - octoprint.util.comm - INFO - Printer reports firmware name "Marlin 1.1.8 (Github)"
2018-08-03 16:01:31,247 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from disk, was still valid
2018-08-03 16:01:31,630 - octoprint.server.preemptive_cache - INFO - Preemptively caching / (ui _default) for {'query_string': 'l10n=en', 'path': '/', 'base_url': 'http://prusa.home:5000/'}
2018-08-03 16:01:31,987 - octoprint.plugins.pluginmanager - INFO - Loaded notice data from disk, was still valid
2018-08-03 16:01:33,632 - octoprint.util.pip - INFO - Using "/home/pi/OctoPrint/venv/bin/python2 -m pip" as command to invoke pip
2018-08-03 16:01:34,621 - octoprint.util.pip - INFO - Using "/home/pi/OctoPrint/venv/bin/python2 -m pip" as command to invoke pip
2018-08-03 16:01:34,621 - octoprint.util.pip - INFO - Using "/home/pi/OctoPrint/venv/bin/python2 -m pip" as command to invoke pip
2018-08-03 16:01:38,772 - octoprint - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/server/views.py", line 398, in index
    response = default_view()
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/server/views.py", line 384, in default_view
    return preemptively_cached()
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/server/util/flask.py", line 895, in decorated_function
    return f(*args, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/server/util/flask.py", line 949, in decorated_function
    return f(*args, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/server/util/flask.py", line 682, in decorated_function
    rv = f_with_duration(*args, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/server/util/flask.py", line 651, in f_with_duration
    return f(*args, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/server/util/flask.py", line 904, in decorated_function
    rv = f(*args, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/server/util/flask.py", line 920, in decorated_function
    rv = f(*args, **kwargs)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/server/views.py", line 371, in make_default_ui
    r = make_response(render_template("index.jinja2", **render_kwargs))
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/Jinja2-2.8.1-py2.7.egg/jinja2/environment.py", line 989, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/Jinja2-2.8.1-py2.7.egg/jinja2/environment.py", line 754, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.4.0.dev1426+g44fcd4e3-py2.7.egg/octoprint/templates/index.jinja2", line 16, in top-level template code
    {% include 'initscript.jinja2' %}
  File "/home/pi/OctoPrint/venv/lib/python2.7/site-packages/OctoPrint-1.4.0.dev1426+g44fcd4e3-py2.7.egg/octoprint/templates/initscript.jinja2", line 39, in top-level template code
    var PERMISSIONS = {{ permissions|tojson }};
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/flask/json.py", line 243, in tojson_filter
    return Markup(htmlsafe_dumps(obj, **kwargs))
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/flask/json.py", line 186, in htmlsafe_dumps
    rv = dumps(obj, **kwargs) \
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/flask/json.py", line 126, in dumps
    rv = _json.dumps(obj, **kwargs)
  File "/usr/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/usr/lib/python2.7/json/encoder.py", line 209, in encode
    chunks = list(chunks)
  File "/usr/lib/python2.7/json/encoder.py", line 442, in _iterencode
    o = _default(o)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/octoprint/server/util/flask.py", line 1436, in default
    return flask.json.JSONEncoder.default(self, obj)
  File "/home/pi/OctoPrint/venv/local/lib/python2.7/site-packages/flask/json.py", line 83, in default
    return _json.JSONEncoder.default(self, o)
  File "/usr/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: Undefined is not JSON serializable
2018-08-03 16:01:38,774 - octoprint.server.preemptive_cache - INFO - ... done in 7.14s
2018-08-03 16:01:40,907 - octoprint.util.pip - INFO - pip installs to /home/pi/OctoPrint/venv/lib/python2.7/site-packages/ (writable -> yes), --user flag needed -> no, virtual env -> yes
2018-08-03 16:01:40,908 - octoprint.util.pip - INFO - ==> pip ok -> yes
2018-08-03 16:01:41,010 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
```

#### Link to contents of Javascript console in the browser

nothing 

I have read the FAQ.

**Comment by foosel** [comment]
That looks like there are still left overs somewhere in the system from an earlier OctoPrint 1.4.0.dev install (see the `PERMISSIONS` bit).

Please try

```
cd ~/OctoPrint
source ./venv/bin/activate
python setup.py clean
pip install .
```

**Comment by gege2b** [comment]
you're right, I was on the commit channel but for some reason that did't work, then I did some channel  switches and I clearly broke something

At first there was only the sarge 0.1.5 problem but once this problem solved, something was still broken

So,thank you now it works

I leave, I have to slap my head with something hard while repeating "you-will-not-mess-again-with-the-packages"

**Comment by foosel** [comment]
Don't beat yourself up over it ;)
