### ISSUE TITLE
string indices must be integers, not unicode during installation

### ISSUE THREAD

**Issue by dedalo88** [foosel/OctoPrint#3023]
#### What were you doing?

I started the Octoprint setup following this instructions page:
https://discourse.octoprint.org/t/setting-up-octoprint-on-a-raspberry-pi-running-raspbian/2337

```
cd ~
sudo apt update
sudo apt install python-pip python-dev python-setuptools python-virtualenv git libyaml-dev build-essential
mkdir OctoPrint && cd OctoPrint
virtualenv venv
source venv/bin/activate
pip install pip --upgrade
pip install https://get.octoprint.org/latest
sudo usermod -a -G tty myUser
sudo usermod -a -G dialout myUser
```
The first time 2018-09-14 the setup worked well, and I was able to reach http://127.0.0.1:5000
Then on 2019-01-27 I updated the system with apt-get and Octoprint following setup again, but I get http error 500:
```
2019-01-27 17:50:12,049 - octoprint.startup - INFO - ******************************************************************************
2019-01-27 17:50:12,053 - octoprint.startup - INFO - Starting OctoPrint 1.3.9
2019-01-27 17:50:12,054 - octoprint.startup - INFO - ******************************************************************************
2019-01-27 17:50:12,167 - octoprint.plugin.core - INFO - Loading plugins from /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins, /home/technology/.octoprint/plugins and installed plugin packages...
2019-01-27 17:50:13,893 - octoprint.plugin.core - WARNING - Plugin "OctoPi Support Plugin" did not pass check
2019-01-27 17:50:14,671 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2019-01-27 17:50:14,683 - octoprint.plugin.core - INFO - Found 10 plugin(s) providing 10 mixin implementations, 8 hook handlers
2019-01-27 17:50:14,816 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2019-01-27 17:50:14,895 - octoprint.server - INFO - Intermediary server started
2019-01-27 17:50:14,896 - octoprint.plugin.core - INFO - Loading plugins from /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins, /home/technology/.octoprint/plugins and installed plugin packages...
2019-01-27 17:50:14,911 - octoprint.plugin.core - WARNING - Plugin "OctoPi Support Plugin" did not pass check
2019-01-27 17:50:15,489 - octoprint.plugin.core - INFO - Found 10 plugin(s) providing 10 mixin implementations, 8 hook handlers
2019-01-27 17:50:15,542 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/technology/.octoprint/uploads...
2019-01-27 17:50:15,545 - octoprint.filemanager.storage - INFO - ... file metadata for /home/technology/.octoprint/uploads initialized successfully.
2019-01-27 17:50:15,592 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2019-01-27 17:50:21,437 - octoprint.util.pip - INFO - Using "/usr/bin/python -m pip" as command to invoke pip
2019-01-27 17:50:26,846 - octoprint.util.pip - INFO - Version of pip is 9.0.1
2019-01-27 17:50:26,850 - octoprint.util.pip - INFO - pip installs to /usr/lib/python2.7/dist-packages (writable -> no), --user flag needed -> yes, virtual env -> no
2019-01-27 17:50:26,851 - octoprint.util.pip - INFO - ==> pip ok -> yes
2019-01-27 17:50:26,856 - octoprint.plugin.core - INFO - Initialized 10 plugin implementation(s)
2019-01-27 17:50:26,866 - octoprint.plugin.core - INFO - 10 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/announcements
|  Core Wizard (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/corewizard
|  CuraEngine (<= 15.04) (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/cura
|  Discovery (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/discovery
|  Logging (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/logging
|  Plugin Manager (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/pluginmanager
|  Printer Safety Check (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/printer_safety_check
|  Software Update (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/virtual_printer
2019-01-27 17:50:26,886 - octoprint.environment - INFO - Detected environment is Python 2.7.13 under Linux (linux2). Details:
|  hardware:
|    cores: 4
|    freq: 1200.0
|    ram: 484048896
|  os:
|    id: linux
|    platform: linux2
|  python:
|    pip: 9.0.1
|    version: 2.7.13
2019-01-27 17:50:26,900 - octoprint.server - INFO - Reset webasset folder /home/technology/.octoprint/generated/webassets...
2019-01-27 17:50:26,905 - octoprint.server - INFO - Reset webasset folder /home/technology/.octoprint/generated/.webassets-cache...
2019-01-27 17:50:27,255 - octoprint.server - INFO - Shutting down intermediary server...
2019-01-27 17:50:27,427 - octoprint.server - INFO - Intermediary server shut down
2019-01-27 17:50:27,431 - octoprint.events - INFO - Processing startup event, this is our first event
2019-01-27 17:50:27,432 - octoprint.events - INFO - Adding 0 events to queue that were held back before startup event
2019-01-27 17:50:27,435 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2019-01-27 17:50:27,442 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2019-01-27 17:50:27,452 - octoprint.plugins.cura - INFO - Path to CuraEngine has not been configured or does not exist (currently set to None), Cura will not be selectable for slicing
2019-01-27 17:50:27,466 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on orangepilite for SSDP
2019-01-27 17:50:27,467 - octoprint.server - INFO - Listening on http://[::]:5000
2019-01-27 17:50:27,937 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from https://plugins.octoprint.org/plugins.json
2019-01-27 17:50:28,031 - octoprint.plugins.announcements - INFO - Loaded channel _important from https://octoprint.org/feeds/important.xml in 0.45s
2019-01-27 17:50:29,202 - octoprint.plugins.announcements - INFO - Loaded channel _releases from https://octoprint.org/feeds/releases.xml in 0.72s
2019-01-27 17:50:29,686 - octoprint.plugins.pluginmanager - INFO - Loaded plugin notices data from https://plugins.octoprint.org/notices.json
2019-01-27 17:50:30,274 - octoprint.plugins.announcements - INFO - Loaded channel _blog from https://octoprint.org/feeds/octoblog.xml in 0.93s
2019-01-27 17:50:30,732 - octoprint.plugins.announcements - INFO - Loaded channel _plugins from https://plugins.octoprint.org/feed.xml in 0.33s
2019-01-27 17:50:31,307 - octoprint.plugins.announcements - INFO - Loaded channel _octopi from https://octoprint.org/feeds/octopi.xml in 0.38s
2019-01-27 17:50:34,934 - octoprint.util.pip - INFO - Using "/usr/bin/python -m pip" as command to invoke pip
2019-01-27 17:50:43,143 - octoprint.util.pip - INFO - pip installs to /usr/local/lib/python2.7/dist-packages/ (writable -> no), --user flag needed -> yes, virtual env -> no
2019-01-27 17:50:43,144 - octoprint.util.pip - INFO - ==> pip ok -> yes
2019-01-27 17:50:43,170 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2019-01-27 17:51:41,519 - octoprint - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/server/views.py", line 412, in index
    response = default_view()
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/server/views.py", line 384, in default_view
    return preemptively_cached()
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/server/util/flask.py", line 894, in decorated_function
    cache.record(data, unless=unless)
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/server/util/flask.py", line 760, in record
    self.add_data(root, entry_data)
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/server/util/flask.py", line 858, in add_data
    existing, other = split_matched_and_unmatched(data, cache_data[root])
TypeError: string indices must be integers, not unicode
2019-01-27 17:51:41,522 - tornado.access - ERROR - 500 GET / (192.168.1.62) 979.24ms
2019-01-27 17:51:41,804 - tornado.access - WARNING - 404 GET /favicon.ico (192.168.1.62) 8.29ms
2019-01-27 17:53:15,920 - octoprint.server - INFO - Shutting down...
2019-01-27 17:53:16,554 - octoprint.events - INFO - Processing shutdown event, this will be our last event
2019-01-27 17:53:16,558 - octoprint.events - INFO - Event loop shut down
2019-01-27 17:53:16,581 - octoprint.server - INFO - Goodbye!
```
Same result in safe mode:
```
2019-01-30 11:08:56,570 - octoprint.startup - INFO - ******************************************************************************
2019-01-30 11:08:56,574 - octoprint.startup - INFO - Starting OctoPrint 1.3.9
2019-01-30 11:08:56,574 - octoprint.startup - INFO - Starting in SAFE MODE. Third party plugins will be disabled!
2019-01-30 11:08:56,575 - octoprint.startup - INFO - ******************************************************************************
2019-01-30 11:08:56,835 - octoprint.plugin.core - INFO - Loading plugins from /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins, /home/technology/.octoprint/plugins and installed plugin packages...
2019-01-30 11:08:59,734 - octoprint.plugin.core - WARNING - Plugin "OctoPi Support Plugin" did not pass check
2019-01-30 11:09:00,160 - octoprint.plugins.discovery - INFO - pybonjour is not installed, Zeroconf Discovery won't be available
2019-01-30 11:09:00,172 - octoprint.plugin.core - INFO - Found 10 plugin(s) providing 10 mixin implementations, 8 hook handlers
2019-01-30 11:09:00,363 - octoprint.server.heartbeat - INFO - Starting server heartbeat, 900.0s interval
2019-01-30 11:09:00,442 - octoprint.server - INFO - Intermediary server started
2019-01-30 11:09:00,442 - octoprint.plugin.core - INFO - Loading plugins from /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins, /home/technology/.octoprint/plugins and installed plugin packages...
2019-01-30 11:09:00,457 - octoprint.plugin.core - WARNING - Plugin "OctoPi Support Plugin" did not pass check
2019-01-30 11:09:00,548 - octoprint.plugin.core - INFO - Found 10 plugin(s) providing 10 mixin implementations, 8 hook handlers
2019-01-30 11:09:00,601 - octoprint.filemanager.storage - INFO - Initializing the file metadata for /home/technology/.octoprint/uploads...
2019-01-30 11:09:00,604 - octoprint.filemanager.storage - INFO - ... file metadata for /home/technology/.octoprint/uploads initialized successfully.
2019-01-30 11:09:00,653 - octoprint.plugins.softwareupdate - INFO - Loaded version cache from disk
2019-01-30 11:09:06,535 - octoprint.util.pip - INFO - Using "/usr/bin/python -m pip" as command to invoke pip
2019-01-30 11:09:11,970 - octoprint.util.pip - INFO - Version of pip is 9.0.1
2019-01-30 11:09:11,974 - octoprint.util.pip - INFO - pip installs to /usr/lib/python2.7/dist-packages (writable -> no), --user flag needed -> yes, virtual env -> no
2019-01-30 11:09:11,974 - octoprint.util.pip - INFO - ==> pip ok -> yes
2019-01-30 11:09:11,980 - octoprint.plugin.core - INFO - Initialized 10 plugin implementation(s)
2019-01-30 11:09:11,990 - octoprint.plugin.core - INFO - 10 plugin(s) registered with the system:
|  Action Command Prompt Support (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/action_command_prompt
|  Announcement Plugin (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/announcements
|  Core Wizard (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/corewizard
|  CuraEngine (<= 15.04) (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/cura
|  Discovery (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/discovery
|  Logging (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/logging
|  Plugin Manager (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/pluginmanager
|  Printer Safety Check (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/printer_safety_check
|  Software Update (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/softwareupdate
|  Virtual Printer (bundled) = /usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/plugins/virtual_printer
2019-01-30 11:09:12,010 - octoprint.environment - INFO - Detected environment is Python 2.7.13 under Linux (linux2). Details:
|  hardware:
|    cores: 4
|    freq: 1200.0
|    ram: 517279744
|  os:
|    id: linux
|    platform: linux2
|  python:
|    pip: 9.0.1
|    version: 2.7.13
2019-01-30 11:09:12,025 - octoprint.server - INFO - Reset webasset folder /home/technology/.octoprint/generated/webassets...
2019-01-30 11:09:12,029 - octoprint.server - INFO - Reset webasset folder /home/technology/.octoprint/generated/.webassets-cache...
2019-01-30 11:09:12,374 - octoprint.server - INFO - Shutting down intermediary server...
2019-01-30 11:09:12,459 - octoprint.server - INFO - Intermediary server shut down
2019-01-30 11:09:12,463 - octoprint.events - INFO - Processing startup event, this is our first event
2019-01-30 11:09:12,465 - octoprint.events - INFO - Adding 0 events to queue that were held back before startup event
2019-01-30 11:09:12,468 - octoprint.filemanager - INFO - Adding backlog items from all storage types to analysis queue...
2019-01-30 11:09:12,475 - octoprint.filemanager - INFO - Added 0 items from storage type "local" to analysis queue
2019-01-30 11:09:12,484 - octoprint.plugins.cura - INFO - Path to CuraEngine has not been configured or does not exist (currently set to None), Cura will not be selectable for slicing
2019-01-30 11:09:12,496 - octoprint.plugins.discovery - INFO - Registered OctoPrint instance on orangepilite for SSDP
2019-01-30 11:09:12,505 - octoprint.server - INFO - Listening on http://[::]:5000
2019-01-30 11:09:12,834 - octoprint.plugins.announcements - INFO - Loaded channel _important from https://octoprint.org/feeds/important.xml in 0.23s
2019-01-30 11:09:12,928 - octoprint.plugins.pluginmanager - INFO - Loaded plugin repository data from https://plugins.octoprint.org/plugins.json
2019-01-30 11:09:13,824 - octoprint.plugins.announcements - INFO - Loaded channel _releases from https://octoprint.org/feeds/releases.xml in 0.57s
2019-01-30 11:09:14,150 - octoprint.plugins.pluginmanager - INFO - Loaded plugin notices data from https://plugins.octoprint.org/notices.json
2019-01-30 11:09:14,275 - octoprint.plugins.announcements - INFO - Loaded channel _blog from https://octoprint.org/feeds/octoblog.xml in 0.3s
2019-01-30 11:09:14,687 - octoprint.plugins.announcements - INFO - Loaded channel _plugins from https://plugins.octoprint.org/feed.xml in 0.29s
2019-01-30 11:09:15,068 - octoprint.plugins.announcements - INFO - Loaded channel _octopi from https://octoprint.org/feeds/octopi.xml in 0.2s
2019-01-30 11:09:19,436 - octoprint.util.pip - INFO - Using "/usr/bin/python -m pip" as command to invoke pip
2019-01-30 11:09:26,797 - octoprint.util.pip - INFO - pip installs to /usr/local/lib/python2.7/dist-packages/ (writable -> no), --user flag needed -> yes, virtual env -> no
2019-01-30 11:09:26,798 - octoprint.util.pip - INFO - ==> pip ok -> yes
2019-01-30 11:09:26,823 - octoprint.plugins.softwareupdate - INFO - Saved version cache to disk
2019-01-30 11:09:52,643 - octoprint - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/server/views.py", line 412, in index
    response = default_view()
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/server/views.py", line 384, in default_view
    return preemptively_cached()
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/server/util/flask.py", line 894, in decorated_function
    cache.record(data, unless=unless)
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/server/util/flask.py", line 760, in record
    self.add_data(root, entry_data)
  File "/usr/local/lib/python2.7/dist-packages/OctoPrint-1.3.9-py2.7.egg/octoprint/server/util/flask.py", line 858, in add_data
    existing, other = split_matched_and_unmatched(data, cache_data[root])
TypeError: string indices must be integers, not unicode
2019-01-30 11:09:52,648 - tornado.access - ERROR - 500 GET / (192.168.1.45) 755.28ms
2019-01-30 11:09:52,704 - tornado.access - WARNING - 404 GET /favicon.ico (192.168.1.45) 8.16ms
2019-01-30 11:09:57,554 - octoprint.server - INFO - Shutting down...
2019-01-30 11:09:58,531 - octoprint.events - INFO - Processing shutdown event, this will be our last event
2019-01-30 11:09:58,534 - octoprint.events - INFO - Event loop shut down
2019-01-30 11:09:58,557 - octoprint.server - INFO - Goodbye!
```

This is the HW board and the OS I use:
https://www.armbian.com/orange-pi-lite/

#### What did you expect to happen?
To be able to reach web console

#### What happened instead?
Http error

#### Did the same happen when running OctoPrint in safe mode?
Yes

#### Version of OctoPrint
1.3.9

#### Operating System running OctoPrint
ARMBIAN 5.70 stable Debian GNU/Linux 9 (stretch) 4.19.13-sunxi

#### Printer model & used firmware incl. version
na

#### Browser and version of browser, operating system running browser
Firefox, Windows 10

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.
[octoprint.log](https://github.com/foosel/OctoPrint/files/2812117/octoprint.log)

**Comment by foosel** [comment]
Looks like for some reason there's some inconsistent internal state in the preemptive cache that leads to misformed data. I don't know yet why or how that's possible and will have to take a look. 

To get things working for you again, please try disabling preemptive caching by setting `devel.cache.preemptive` in `config.yaml` to `false`. See also [the docs here](http://docs.octoprint.org/en/master/configuration/config_yaml.html#development-settings).

Side note: It looks like you have OctoPrint installed globally. That is discouraged, the supported way is to use a virtual environment to rule out any system package versions from causing problems (*might* be a factor here, but only *might*). Also 1.3.10 has been out since early December.

**Comment by dedalo88** [comment]
I updated the `config.yaml` file as you indicate and it worked. 
Actually I don't know the difference between global installation and virtual environment installation, where could I make things wrong?
This is my `preemptive_cache_config.yaml` file:

```
V//
```

**Comment by dedalo88** [comment]
yes I did, I installed octoprint until the web wizard start, then I turned the board off to continue later.
Thank you for support :)
