### ISSUE TITLE
[1.3.11rc1] ETag calculation for main view can't handle unicode plugin template vars

### ISSUE THREAD

**Issue by foosel** [foosel/OctoPrint#3088]
### Problem

  1. Install [Cost plugin](https://github.com/jasiek/OctoPrint-Cost)
  2. Restart & Reload:

```
2019-03-28 11:47:25,543 - octoprint - ERROR - Exception on / [GET]
Traceback (most recent call last):
  File "/home/pi/oprint/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/pi/oprint/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/pi/oprint/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/pi/oprint/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/pi/oprint/lib/python2.7/site-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/pi/oprint/lib/python2.7/site-packages/octoprint/server/views.py", line 199, in index
    enable_timelapse] + sorted(["{}:{}".format(k, v) for k, v in _plugin_vars.items()])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u20ac' in position 0: ordinal not in range(128)
```

### Solution

Use unicode instead of str for ETag parts.

**Comment by foosel** [comment]
1.3.11rc2 was just released
