### ISSUE TITLE
printjob cancelled right after starting

### ISSUE THREAD

**Issue by Leprechaun91** [foosel/OctoPrint#3251]
#### What did you expect to happen?
Printer should start printing
#### What happened instead?
Printing is started and heating starts, seconds later status changed to "cancelling"
#### Did the same happen when running OctoPrint in safe mode?
yes

#### Version of OctoPrint
1.3.11

#### Operating System running OctoPrint
Raspi

#### Screenshot(s)/video(s) showing the problem:

I have read the FAQ.

**Comment by Leprechaun91** [comment]
`

2019-08-16 14:01:39,023 - octoprint.plugins.telegram - DEBUG - Saving data: {u'chats': {u'382113096': {u'commands': {u'/filament': True, u'/upload': True, u'/con': True, u'/print': True, u'/gif': True, u'/status': True, u'/user': True, u'/abort': True, u'/dontshutup': True, u'/shutup': True, u'/files': True, u'/supergif': True, u'/ctrl': True, u'/togglepause': True, u'/tune': True, u'/settings': True, u'/sys': True}, u'title': u'Julian - Kusenberg - ', u'image': u'/plugin/telegram/img/user/pic382113096.jpg', u'send_notifications': True, u'private': True, u'allow_users': False, u'notifications': {u'StatusPrinting': False, u'PrintDone': True, u'ZChange': True, u'PrinterStart': True, u'PrintFailed': True, u'StatusNotPrinting': False, u'PrintStarted': True, u'PrintResumed': False, u'PrintPaused': True, u'PrinterShutdown': True}, u'newUsr': False, u'new': False, u'type': u'PRIVATE', u'id': u'382113096', u'accept_commands': True}}}
2019-08-16 14:01:45,594 - octoprint.server.util.sockjs - INFO - User admin logged in on the socket from client ::1
2019-08-16 14:01:51,688 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature
2019-08-16 14:01:53,331 - octoprint.server.preemptive_cache - INFO - ... done in 14.39s
2019-08-16 14:02:01,614 - octoprint.plugins.telegram.listener - DEBUG - listener: sending request with offset 1...
2019-08-16 14:02:01,816 - tornado.access - WARNING - 409 GET /api/printer?exclude=sd,history (::ffff:192.168.2.63) 11.85ms
2019-08-16 14:02:22,342 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature
2019-08-16 14:02:31,863 - octoprint.plugins.telegram.listener - DEBUG - listener: sending request with offset 1...
2019-08-16 14:02:52,393 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature
2019-08-16 14:03:01,876 - tornado.access - WARNING - 409 GET /api/printer?exclude=sd,history (::ffff:192.168.2.63) 23.07ms
2019-08-16 14:03:02,103 - octoprint.plugins.telegram.listener - DEBUG - listener: sending request with offset 1...
2019-08-16 14:03:22,168 - octoprint.util.comm - INFO - Changing monitoring state from "Offline" to "Opening serial port"
2019-08-16 14:03:22,174 - octoprint.util.comm - INFO - Changing monitoring state from "Opening serial port" to "Connecting"
2019-08-16 14:03:22,182 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2019-08-16 14:03:22,441 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature
2019-08-16 14:03:23,804 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2019-08-16 14:03:32,020 - octoprint.util.comm - INFO - Changing monitoring state from "Connecting" to "Operational"
2019-08-16 14:03:32,048 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2019-08-16 14:03:32,105 - octoprint.util.comm - INFO - Printer reports firmware name "Marlin SkyNet3D-V2.3.2 (Github)"
2019-08-16 14:03:32,312 - octoprint.plugins.telegram.listener - DEBUG - listener: sending request with offset 1...
2019-08-16 14:03:49,534 - octoprint.printer.standard.job - INFO - Print job selected - origin: local, path: Back.gcode, owner: admin, user: admin
2019-08-16 14:03:49,546 - octoprint.plugins.DisplayLayerProgress - INFO - File selected. Determining number of layers.
2019-08-16 14:03:52,125 - octoprint.util.comm - INFO - Changing monitoring state from "Operational" to "Starting"
2019-08-16 14:03:52,137 - octoprint.printer.standard.job - INFO - Print job started - origin: local, path: Back.gcode, owner: admin, user: admin
2019-08-16 14:03:52,522 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature
2019-08-16 14:03:52,771 - octoprint.util.comm - INFO - Changing monitoring state from "Starting" to "Printing"
2019-08-16 14:03:52,963 - octoprint.util.comm - INFO - M110 detected, setting current line number to 0
2019-08-16 14:03:53,167 - octoprint.plugins.cancelobject - INFO - Tracking Extrusion
2019-08-16 14:04:02,576 - octoprint.plugins.telegram.listener - DEBUG - listener: sending request with offset 1...
2019-08-16 14:04:08,919 - octoprint.plugins.DisplayLayerProgress - INFO - Printing started. Detailed progress started.{'origin': 'local', 'name': u'Back.gcode', 'file': u'/home/pi/.octoprint/uploads/Back.gcode', 'owner': 'admin', 'path': u'Back.gcode', 'user': 'admin', 'size': 22129517L, 'filename': u'Back.gcode'}
2019-08-16 14:04:08,939 - octoprint.plugins.IFTTT - INFO - .name
2019-08-16 14:04:08,940 - octoprint.plugins.IFTTT - INFO - .origin
2019-08-16 14:04:08,943 - octoprint.plugins.IFTTT - INFO - 
2019-08-16 14:04:13,253 - octoprint.plugins.filamentreload - INFO - Printing aborted: no filament detected!
2019-08-16 14:04:13,264 - octoprint.util.comm - INFO - Changing monitoring state from "Printing" to "Cancelling"
2019-08-16 14:04:13,300 - octoprint.printer.standard.job - INFO - Print job cancelled - origin: local, path: Back.gcode, owner: admin, user: None
2019-08-16 14:04:13,355 - octoprint.plugins.filamentreload - INFO - PrintStarted: Enabling filament sensor.
2019-08-16 14:04:13,781 - octoprint.printer.standard - ERROR - Exception while pushing current data to callback <layerdisplay.LayerDisplayPlugin object at 0x72ca4530>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 196, in _sendCurrentDataCallbacks
    callback.on_printer_send_current_data(copy.deepcopy(data))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/layerdisplay/__init__.py", line 46, in on_printer_send_current_data
    progress = data['progress']['completion'] / 100
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
2019-08-16 14:04:14,615 - octoprint.printer.standard - ERROR - Exception while pushing current data to callback <layerdisplay.LayerDisplayPlugin object at 0x72ca4530>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 196, in _sendCurrentDataCallbacks
    callback.on_printer_send_current_data(copy.deepcopy(data))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/layerdisplay/__init__.py", line 46, in on_printer_send_current_data
    progress = data['progress']['completion'] / 100
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
2019-08-16 14:04:15,616 - octoprint.printer.standard - ERROR - Exception while pushing current data to callback <layerdisplay.LayerDisplayPlugin object at 0x72ca4530>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 196, in _sendCurrentDataCallbacks
    callback.on_printer_send_current_data(copy.deepcopy(data))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/layerdisplay/__init__.py", line 46, in on_printer_send_current_data
    progress = data['progress']['completion'] / 100
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
2019-08-16 14:04:16,623 - octoprint.printer.standard - ERROR - Exception while pushing current data to callback <layerdisplay.LayerDisplayPlugin object at 0x72ca4530>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 196, in _sendCurrentDataCallbacks
    callback.on_printer_send_current_data(copy.deepcopy(data))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/layerdisplay/__init__.py", line 46, in on_printer_send_current_data
    progress = data['progress']['completion'] / 100
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
2019-08-16 14:04:16,646 - octoprint.plugins.telegram - DEBUG - Got an event: PrintStarted Payload: {'origin': 'local', 'name': u'Back.gcode', 'file': u'/home/pi/.octoprint/uploads/Back.gcode', 'owner': 'admin', 'path': u'Back.gcode', 'user': 'admin', 'size': 22129517L, 'filename': u'Back.gcode'}
2019-08-16 14:04:16,662 - octoprint.plugins.telegram.TMSG - DEBUG - Printer Status{'progress': {'completion': None, 'printTimeLeftOrigin': None, 'printTime': None, 'printTimeLeft': None, 'filepos': None}, 'state': {'text': 'Cancelling', 'flags': {'cancelling': True, 'paused': False, 'operational': True, 'pausing': False, 'printing': True, 'resuming': False, 'sdReady': False, 'error': False, 'ready': False, 'finishing': False, 'closedOrError': False}}, 'currentZ': None, 'job': {'averagePrintTime': None, 'lastPrintTime': None, 'user': 'admin', 'file': {'origin': 'local', 'name': u'Back.gcode', 'date': 1565355682, 'path': u'Back.gcode', 'display': u'Back.gcode', 'size': 22129517L}, 'estimatedPrintTime': 85248.26248034717, 'filament': {u'tool0': {u'volume': 1276.3610792584186, u'length': 180568.15047219675}}}, 'offsets': {}}
2019-08-16 14:04:16,667 - octoprint.plugins.telegram.TMSG - DEBUG - TEMPS - {'chamber': {'actual': None, 'target': None, 'offset': 0}, 'bed': {'actual': 39.6, 'target': 87.0, 'offset': 0}, 'tool0': {'actual': 30.3, 'target': 0.0, 'offset': 0}}
2019-08-16 14:04:16,672 - octoprint.plugins.telegram - INFO - An Exception in get final time : unsupported type for timedelta seconds component: str
2019-08-16 14:04:16,674 - octoprint.plugins.telegram.TMSG - DEBUG - VARS - {'event': 'PrintStarted', 'status': {'progress': {'completion': None, 'printTimeLeftOrigin': None, 'printTime': None, 'printTimeLeft': None, 'filepos': None}, 'state': {'text': 'Cancelling', 'flags': {'cancelling': True, 'paused': False, 'operational': True, 'pausing': False, 'printing': True, 'resuming': False, 'sdReady': False, 'error': False, 'ready': False, 'finishing': False, 'closedOrError': False}}, 'currentZ': None, 'job': {'averagePrintTime': None, 'lastPrintTime': None, 'user': 'admin', 'file': {'origin': 'local', 'name': u'Back.gcode', 'date': 1565355682, 'path': u'Back.gcode', 'display': u'Back.gcode', 'size': 22129517L}, 'estimatedPrintTime': 85248.26248034717, 'filament': {u'tool0': {u'volume': 1276.3610792584186, u'length': 180568.15047219675}}}, 'offsets': {}}, 'e2_target': 0.0, 'e1_temp': 30.3, 'payload': {'origin': 'local', 'name': u'Back.gcode', 'file': u'/home/pi/.octoprint/uploads/Back.gcode', 'owner': 'admin', 'path': u'Back.gcode', 'user': 'admin', 'size': 22129517L, 'filename': u'Back.gcode'}, 'time_left': '[Unknown]', 'self': <octoprint_telegram.telegramNotifications.TMSG instance at 0x6aac0670>, 'kwargs': {'with_gif': False, 'with_image': True, 'event': 'PrintStarted'}, 'percent': 0, 'bed_temp': 39.6, 'e1_target': 0.0, 'temps': {'chamber': {'actual': None, 'target': None, 'offset': 0}, 'bed': {'actual': 39.6, 'target': 87.0, 'offset': 0}, 'tool0': {'actual': 30.3, 'target': 0.0, 'offset': 0}}, 'bed_target': 87.0, 'time_finish': '', 'file': u'Back.gcode', 'time_done': '00:00:00', 'path': u'Back.gcode', 'z': 0.0, 'e2_temp': 0.0}
2019-08-16 14:04:16,679 - octoprint.plugins.telegram.TMSG - DEBUG - Sending Notification: Started printing Back.gcode.
2019-08-16 14:04:16,681 - octoprint.plugins.telegram - DEBUG - Send_msg() found event: PrintStarted
2019-08-16 14:04:16,683 - octoprint.plugins.telegram - INFO - Sending a message: Started printing Back.gcode. with_image=True with_gif=False chatID= 382113096
2019-08-16 14:04:16,685 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:16,764 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:16,766 - octoprint.plugins.telegram - DEBUG - data so far: {'disable_web_page_preview': True}
2019-08-16 14:04:16,767 - octoprint.plugins.telegram - DEBUG - Sending with image.. 382113096
2019-08-16 14:04:17,220 - octoprint.plugins.telegram - DEBUG - Sending finished. 200
2019-08-16 14:04:17,310 - octoprint.plugins.filamentmanager - INFO - Filament used: 0.0 mm (tool0)
2019-08-16 14:04:17,614 - octoprint.printer.standard - ERROR - Exception while pushing current data to callback <layerdisplay.LayerDisplayPlugin object at 0x72ca4530>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 196, in _sendCurrentDataCallbacks
    callback.on_printer_send_current_data(copy.deepcopy(data))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/layerdisplay/__init__.py", line 46, in on_printer_send_current_data
    progress = data['progress']['completion'] / 100
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
2019-08-16 14:04:18,616 - octoprint.printer.standard - ERROR - Exception while pushing current data to callback <layerdisplay.LayerDisplayPlugin object at 0x72ca4530>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 196, in _sendCurrentDataCallbacks
    callback.on_printer_send_current_data(copy.deepcopy(data))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/layerdisplay/__init__.py", line 46, in on_printer_send_current_data
    progress = data['progress']['completion'] / 100
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
2019-08-16 14:04:19,613 - octoprint.printer.standard - ERROR - Exception while pushing current data to callback <layerdisplay.LayerDisplayPlugin object at 0x72ca4530>
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/octoprint/printer/standard.py", line 196, in _sendCurrentDataCallbacks
    callback.on_printer_send_current_data(copy.deepcopy(data))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/layerdisplay/__init__.py", line 46, in on_printer_send_current_data
    progress = data['progress']['completion'] / 100
TypeError: unsupported operand type(s) for /: 'NoneType' and 'int'
2019-08-16 14:04:20,315 - octoprint.plugins.DisplayLayerProgress - INFO - Printing stopped. Detailed progress stopped.
2019-08-16 14:04:20,374 - octoprint.plugins.filamentreload - INFO - PrintCancelled: Disabling filament sensor.
2019-08-16 14:04:20,847 - octoprint.plugins.DisplayLayerProgress - INFO - Printing stopped. Detailed progress stopped.
2019-08-16 14:04:20,865 - octoprint.plugins.IFTTT - INFO - .name
2019-08-16 14:04:20,866 - octoprint.plugins.IFTTT - INFO - .reason
2019-08-16 14:04:20,867 - octoprint.plugins.IFTTT - INFO - .origin
2019-08-16 14:04:20,878 - octoprint.plugins.filamentreload - INFO - PrintFailed: Disabling filament sensor.
2019-08-16 14:04:21,110 - octoprint.plugins.telegram - DEBUG - Got an event: PrintFailed Payload: {'origin': 'local', 'reason': 'cancelled', 'name': u'Back.gcode', 'file': u'/home/pi/.octoprint/uploads/Back.gcode', 'position': {'e': None, 'f': None, 't': None, 'y': None, 'x': None, 'z': None}, 'owner': 'admin', 'path': u'Back.gcode', 'size': 22129517L, 'time': 21.17519358299998, 'filename': u'Back.gcode'}
2019-08-16 14:04:21,119 - octoprint.plugins.telegram.TMSG - DEBUG - Printer Status{'progress': {'completion': None, 'printTimeLeftOrigin': None, 'printTime': None, 'printTimeLeft': None, 'filepos': None}, 'state': {'text': 'Cancelling', 'flags': {'cancelling': True, 'paused': False, 'operational': True, 'pausing': False, 'printing': True, 'resuming': False, 'sdReady': False, 'error': False, 'ready': False, 'finishing': False, 'closedOrError': False}}, 'currentZ': None, 'job': {'averagePrintTime': None, 'lastPrintTime': None, 'user': 'admin', 'file': {'origin': 'local', 'name': u'Back.gcode', 'date': 1565355682, 'path': u'Back.gcode', 'display': u'Back.gcode', 'size': 22129517L}, 'estimatedPrintTime': 85248.26248034717, 'filament': {u'tool0': {u'volume': 1276.3610792584186, u'length': 180568.15047219675}}}, 'offsets': {}}
2019-08-16 14:04:21,120 - octoprint.plugins.telegram.TMSG - DEBUG - TEMPS - {'chamber': {'actual': None, 'target': None, 'offset': 0}, 'bed': {'actual': 40.5, 'target': 87.0, 'offset': 0}, 'tool0': {'actual': 30.2, 'target': 0.0, 'offset': 0}}
2019-08-16 14:04:21,123 - octoprint.plugins.telegram - INFO - An Exception in get final time : unsupported type for timedelta seconds component: str
2019-08-16 14:04:21,124 - octoprint.plugins.telegram.TMSG - DEBUG - VARS - {'event': 'PrintFailed', 'status': {'progress': {'completion': None, 'printTimeLeftOrigin': None, 'printTime': None, 'printTimeLeft': None, 'filepos': None}, 'state': {'text': 'Cancelling', 'flags': {'cancelling': True, 'paused': False, 'operational': True, 'pausing': False, 'printing': True, 'resuming': False, 'sdReady': False, 'error': False, 'ready': False, 'finishing': False, 'closedOrError': False}}, 'currentZ': None, 'job': {'averagePrintTime': None, 'lastPrintTime': None, 'user': 'admin', 'file': {'origin': 'local', 'name': u'Back.gcode', 'date': 1565355682, 'path': u'Back.gcode', 'display': u'Back.gcode', 'size': 22129517L}, 'estimatedPrintTime': 85248.26248034717, 'filament': {u'tool0': {u'volume': 1276.3610792584186, u'length': 180568.15047219675}}}, 'offsets': {}}, 'e2_target': 0.0, 'e1_temp': 30.2, 'payload': {'origin': 'local', 'reason': 'cancelled', 'name': u'Back.gcode', 'file': u'/home/pi/.octoprint/uploads/Back.gcode', 'position': {'e': None, 'f': None, 't': None, 'y': None, 'x': None, 'z': None}, 'owner': 'admin', 'path': u'Back.gcode', 'size': 22129517L, 'time': 21.17519358299998, 'filename': u'Back.gcode'}, 'time_left': '[Unknown]', 'self': <octoprint_telegram.telegramNotifications.TMSG instance at 0x6aac0670>, 'kwargs': {'with_gif': True, 'with_image': False, 'event': 'PrintFailed'}, 'percent': 0, 'bed_temp': 40.5, 'e1_target': 0.0, 'temps': {'chamber': {'actual': None, 'target': None, 'offset': 0}, 'bed': {'actual': 40.5, 'target': 87.0, 'offset': 0}, 'tool0': {'actual': 30.2, 'target': 0.0, 'offset': 0}}, 'bed_target': 87.0, 'time_finish': '', 'file': u'Back.gcode', 'time_done': '00:00:00', 'path': u'Back.gcode', 'z': 0.0, 'e2_temp': 0.0}
2019-08-16 14:04:21,127 - octoprint.plugins.telegram.TMSG - DEBUG - Sending Notification: Printing Back.gcode failed.
2019-08-16 14:04:21,131 - octoprint.plugins.telegram - DEBUG - Send_msg() found event: PrintFailed
2019-08-16 14:04:21,137 - octoprint.plugins.telegram - INFO - Sending a message: Printing Back.gcode failed. with_image=False with_gif=True chatID= 382113096
2019-08-16 14:04:21,139 - octoprint.plugins.telegram - DEBUG - data so far: {'disable_web_page_preview': True}
2019-08-16 14:04:21,141 - octoprint.plugins.telegram - DEBUG - Sending without image.. 382113096
2019-08-16 14:04:21,649 - octoprint.plugins.telegram - DEBUG - Sending finished. 200
2019-08-16 14:04:21,706 - octoprint.plugins.telegram - INFO - Will try to create a gif 
2019-08-16 14:04:22,016 - octoprint.plugins.telegram - INFO - will try to save image in path /home/pi/.octoprint/data/telegram/tmpgif
2019-08-16 14:04:22,017 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:22,828 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature
2019-08-16 14:04:22,881 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:23,449 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:23,572 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:24,151 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:24,270 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:24,835 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:24,865 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:25,412 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:25,472 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:26,021 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:26,063 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:26,612 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:26,666 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:27,215 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:27,266 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:27,816 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:27,866 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:28,414 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:28,474 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:29,023 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:29,072 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:29,623 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:29,665 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:30,214 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:30,267 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:30,814 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:30,867 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:31,417 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:31,469 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:32,022 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:32,064 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:32,615 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:32,666 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:32,967 - octoprint.plugins.telegram.listener - DEBUG - listener: sending request with offset 1...
2019-08-16 14:04:33,215 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:33,262 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:33,814 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:33,867 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:34,418 - octoprint.plugins.telegram - DEBUG - Snapshot URL: http://127.0.0.1:1111/?action=snapshot
2019-08-16 14:04:34,468 - octoprint.plugins.telegram - DEBUG - Image transformations [H:False, V:False, R:False]
2019-08-16 14:04:52,973 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature
2019-08-16 14:05:03,176 - octoprint.plugins.telegram.listener - DEBUG - listener: sending request with offset 1...
2019-08-16 14:05:23,031 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature
2019-08-16 14:05:33,474 - octoprint.plugins.telegram.listener - DEBUG - listener: sending request with offset 1...
2019-08-16 14:05:47,173 - octoprint.util.comm - INFO - Changing monitoring state from "Cancelling" to "Offline"
2019-08-16 14:05:49,251 - octoprint.plugins.telegram - DEBUG - Testing token 111111111:AAAa1aaaAa1AAaAa1AAa1aaAAAAaaAaaAaa
2019-08-16 14:05:52,104 - tornado.access - WARNING - 409 GET /api/printer?exclude=sd,history (::ffff:192.168.2.63) 12.74ms
2019-08-16 14:05:52,302 - tornado.access - WARNING - 409 GET /api/printer?exclude=sd,history (::ffff:192.168.2.63) 10.28ms
2019-08-16 14:05:53,085 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature
2019-08-16 14:06:02,198 - tornado.access - WARNING - 409 GET /api/printer?exclude=sd,history (::ffff:192.168.2.63) 18.67ms
2019-08-16 14:06:03,871 - octoprint.plugins.telegram.listener - DEBUG - listener: sending request with offset 1...
2019-08-16 14:06:23,178 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature
2019-08-16 14:06:34,289 - octoprint.plugins.telegram.listener - DEBUG - listener: sending request with offset 1...
2019-08-16 14:06:53,231 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature
2019-08-16 14:07:02,162 - tornado.access - WARNING - 409 GET /api/printer?exclude=sd,history (::ffff:192.168.2.63) 20.72ms
2019-08-16 14:07:04,634 - octoprint.plugins.telegram.listener - DEBUG - listener: sending request with offset 1...
2019-08-16 14:07:23,287 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature
2019-08-16 14:07:34,997 - octoprint.plugins.telegram.listener - DEBUG - listener: sending request with offset 1...
2019-08-16 14:07:53,346 - octoprint.plugins.navbartemp - INFO - Checking SoC internal temperature
2019-08-16 14:07:54,047 - tornado.application - ERROR - Uncaught exception GET /downloads/logs/octoprint.log (::ffff:192.168.2.46)
Traceback (most recent call last):
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/web.py", line 1512, in _execute
    result = yield result
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/gen.py", line 1055, in run
    value = future.result()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/web.py", line 2422, in get
    yield self.flush()
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/web.py", line 953, in flush
    return self.request.connection.write(chunk, callback=callback)
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/http1connection.py", line 437, in write
    self._pending_write = self.stream.write(self._format_chunk(chunk))
  File "/home/pi/oprint/local/lib/python2.7/site-packages/tornado/http1connection.py", line 412, in _format_chunk
    "Tried to write more data than Content-Length")
HTTPOutputError: Tried to write more data than Content-Length
2019-08-16 14:07:54,053 - tornado.general - ERROR - Cannot send error response after headers written
``

**Comment by tedder** [comment]
Run in safe mode and upload that log.

**Comment by bastilian** [comment]
These lines of the log might be an indicator what is happening:
```
2019-08-16 14:04:08,943 - octoprint.plugins.IFTTT - INFO -
2019-08-16 14:04:13,253 - octoprint.plugins.filamentreload - INFO - Printing aborted: no filament detected!
2019-08-16 14:04:13,264 - octoprint.util.comm - INFO - Changing monitoring state from "Printing" to "Cancelling"
```

If you have a filament sensor setup, ensure it is pluggged in correctly, configured correctly and working as it should.

Additionally it appears the telegram plugin fails to send a notification, which is the greater part of the rest of the log.

**Comment by foosel** [comment]
As already pointed out, that looks like its caused by your third party filament detector plugin detecting a lack of filament and cancelling the print.
