### ISSUE TITLE
Error during upgrade process to 1.3.12

### ISSUE THREAD

**Issue by nidsche** [foosel/OctoPrint#3312]
When upgrading octoprint to version 1.3.12 pandas is downloaded from https://files.pythonhosted.org/packages/b2/4c/b6f966ac91c5670ba4ef0b0b5613b5379e3c7abdfad4e7b89a87d73bae13/pandas-0.24.2.tar.gz
The system tries to install pandas afterwards and calls the setup routine via 
python setup.py install 
this pandas module is not compatible with python 2. at the end of the setup routine it states:

2019-10-22 13:37:39,226 > Collecting pandas (from OctoPrint-Stats==2.0.2)
2019-10-22 13:37:41,355 > Downloading https://files.pythonhosted.org/packages/b2/4c/b6f966ac91c5670ba4ef0b0b5613b5379e3c7abdfad4e7b89a87d73bae13/pandas-0.24.2.tar.gz (11.8MB)
2019-10-22 13:38:01,747 > Complete output from command python setup.py egg_info:
2019-10-22 13:38:01,748 > Traceback (most recent call last):
2019-10-22 13:38:01,749 > File "<string>", line 1, in <module>
2019-10-22 13:38:01,750 > File "/tmp/pip-build-1Njxs0/pandas/setup.py", line 746, in <module>
2019-10-22 13:38:01,751 > **setuptools_kwargs)
[...]
2019-10-22 13:38:01,770 > File "/tmp/easy_install-wLSVrx/numpy-1.17.3/setup.py", line 31, in <module>
2019-10-22 13:38:01,770 >
2019-10-22 13:38:01,771 > RuntimeError: Python version >= 3.5 required.
2019-10-22 13:38:01,771 >
2019-10-22 13:38:01,771 > ----------------------------------------
2019-10-22 13:38:01,776 ! Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1Njxs0/pandas/

additionally python3 is missing the setuptools in the default setup

**Comment by foosel** [comment]
OctoPrint doesn't have a dependency on pandas. What's visible in your log there is an upgrade in progress of a third party plugin "OctoPrint-Stats" to verison 2.0.2. I do not control this plugin. You should report this issue with them.
