### ISSUE TITLE
AssertionError inside API endpoints

### ISSUE THREAD

**Issue by jminardi** [foosel/OctoPrint#974]
1. What were you doing?

Running a print

2. What did you expect to happen?

Print to finish to completion

3. What happened instead?

The whole raspberry pi locked up, the OctoPrint interface said lost connection, and I could no longer SSH into the machine.

4. Branch & Commit or Version of OctoPrint:

Version: 1.1.1-994-gcfb23f6 (master branch)

5. Printer model & used firmware incl. version
   (if applicable - always include if unsure):

Marlin latest "Integration" branch

6. Browser and Version of Browser, Operating 
   System running Browser (if applicable - always 
   include if unsure):

Chome on windows

7. Link to octoprint.log on gist.github.com or pastebin.com
   (ALWAYS INCLUDE AND DO NOT TRUNCATE):

http://pastebin.com/Yhhg7eur

8. Link to contents of terminal tab or serial.log on 
   gist.github.com or pastebin.com (if applicable - always 
   include if unsure or reporting communication issues AND
   DO NOT TRUNCATE):

Not logged (I am re-running the same print with serial logging on and will update if it happens again)

9. Link to contents of Javascript console in the browser 
   on gist.github.com or pastebin.com or alternatively a
   screenshot (if applicable - always include if unsure
   or reporting UI issues):

N/A

10. Screenshot(s) showing the problem (if applicable - always
    include if unsure or reporting UI issues):

N/A

I have read the FAQ.

A snippet of the relevant errors. See linked octoprint.log for full errors.

```python
1970-01-01 00:00:38,899 - octoprint - ERROR - Exception on /api/printer [OPTIONS]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/sessions.py", line 326, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous-0.24-py2.7.egg/itsdangerous.py", line 566, in dumps
    rv = self.make_signer(salt).sign(payload)
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous-0.24-py2.7.egg/itsdangerous.py", line 409, in sign
    timestamp = base64_encode(int_to_bytes(self.get_timestamp()))
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous-0.24-py2.7.egg/itsdangerous.py", line 220, in int_to_bytes
    assert num >= 0
AssertionError
1970-01-01 00:00:38,920 - octoprint - ERROR - Exception on /api/job [OPTIONS]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1479, in full_dispatch_request
    response = self.process_response(response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 1693, in process_response
    self.save_session(ctx.session, response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/app.py", line 837, in save_session
    return self.session_interface.save_session(self, session, response)
  File "/usr/local/lib/python2.7/dist-packages/Flask-0.10.1-py2.7.egg/flask/sessions.py", line 326, in save_session
    val = self.get_signing_serializer(app).dumps(dict(session))
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous-0.24-py2.7.egg/itsdangerous.py", line 566, in dumps
    rv = self.make_signer(salt).sign(payload)
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous-0.24-py2.7.egg/itsdangerous.py", line 409, in sign
    timestamp = base64_encode(int_to_bytes(self.get_timestamp()))
  File "/usr/local/lib/python2.7/dist-packages/itsdangerous-0.24-py2.7.egg/itsdangerous.py", line 220, in int_to_bytes
    assert num >= 0
AssertionError
```

**Comment by foosel** [comment]
> The whole raspberry pi locked up, the OctoPrint interface said lost connection, and **I could no longer SSH into the machine.**

That doesn't sound like it could be caused by the exception you were seeing in the log but like an actual full blown crash, especially since after the exception there was another client connection attempt logged.

What is a bit odd about this whole log is the timestamping. The exceptions occurred in a segment where the clock suddenly decided that it was a couple of minutes after the unix epoch, then right after the exceptions the time jumped back to the current one. Since that exception is apparently timestamp related (see the `timestamp = base64_encode...` part) you really should investigate what your system clock did there, and also if there is anything in the syslog of the machine.

Chances are very very high that it's unrelated to OctoPrint (the fact that no octoprint package is even present in that stack trace also make me think that) and rather caused by some environmental issues.
